package com.praxedo.securefiles.domain.file.valueobject;

import java.util.Objects;
import java.util.UUID;

/** Identifier of a stored file. Generated by the server, never by the caller. */
public record FileId(UUID value) {

    public FileId {
        Objects.requireNonNull(value, "file id");
    }

    public static FileId random() {
        return new FileId(UUID.randomUUID());
    }

    public static FileId of(String value) {
        return new FileId(UUID.fromString(value));
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
